Shopify pos article docs
trellixio/trybeans-mintlify pull request #126
Opened 2024-11-22 15:17 UTC by Aduralere54256703

2024-12-09 12:21 UTC, Aduralere54256703 commented
@thetallralph 
I want to clarify If the Shopify POS article can placed on the existing article in this section?

2024-12-10 16:00 UTC, thetallralph requested changes
@Aduralere54256703 You should make your change upon the existing main document.
You should not delete the existing content like you did here.

PR is rejected

2024-12-11 08:11 UTC, Aduralere54256703 commented
@thetallralph 
The changes have been made.

2025-01-06 18:33 UTC, thetallralph commented
I will close this PR as it

2025-01-06 18:33 UTC, closed without merging

2025-01-13 10:05 UTC, Aduralere54256703 commented
@thetallralph 
This branch closed. Do you think I should create a new branch for it or the article is not needed ?