Shopify uninstallation article docs
trellixio/trybeans-mintlify pull request #128
Opened 2024-11-22 15:19 UTC by Aduralere54256703

2024-12-10 15:59 UTC, thetallralph requested changes
@Aduralere54256703 You should make your change upon the existing main document.
You should not delete the existing content like you did here.

PR is rejected

2024-12-13 14:04 UTC, thetallralph commented
@Aduralere54256703 Don't forget to ask for review.

2024-12-13 14:07 UTC, thetallralph commented
@Aduralere54256703 Why does the BigCommerce file has changed here but the only think that was supposed to change was Shopify ?

2024-12-13 14:18 UTC, Aduralere54256703 commented
@thetallralph 
The merge we conducted during the conflict resolution seems to be the reason, I assume.

2025-01-06 18:51 UTC, thetallralph commented
I will move the change to new branch as it seems there too much unnecessary file change here.

2025-01-06 18:51 UTC, closed without merging