Feature/integrations bigcommerce
trellixio/trybeans-mintlify pull request #46
Opened 2024-10-04 14:39 UTC by Aduralere54256703

corrections made to this branch

2024-10-04 16:04 UTC, harlick-b submitted a review, later dismissed
ok

2024-10-07 10:54 UTC, harlick-b reviewed
Check comment

2024-10-07 10:54 UTC, harlick-b commented on assets/images/integrations/bigcommerce/Reinstall.gif
Image name should start with a lowercase character

2024-10-31 15:11 UTC, thetallralph requested changes
@Aduralere54256703 
I made some quick change:
- Updated the integration URL to reflect our new domain (from bns.re to trybeans.com)
- Reformatted the Order Logs section to use bullet points for better scanability

But in order to have more consistency with other platform article, you should  add a new "Rewards Page" section.

2024-11-05 08:28 UTC, thetallralph approved these changes
ok

2024-11-05 08:28 UTC, thetallralph commented on assets/images/integrations/bigcommerce/Reinstall.gif
ok

2024-11-05 08:28 UTC, merged